version: "3.1"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data_vol:/data/db
  
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
    ports:
      - 8081:8081
    depends_on:
      - mongo


volumes:
  mongo_data_vol:
