version: "3.1"
services:

  elasticsearch-geo:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 19200:9200
      - 19300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana-geo:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - 15601:5601
    depends_on:
      - elasticsearch-geo

  logstash-geo:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/montevideo-template.json:/etc/logstash/templates/montevideo-template.json
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/datos:/tmp/datos
    ports:
      - 15000:5000
    environment:
      LS_JAVA_OPTS: "-Xmx500m -Xms500m"
    depends_on:
      - elasticsearch-geo

  jupyter-geo:
    image: jupyter-im
    build: jupyter/
    ports:
      - 18888:8888
    volumes:
      - ./jupyter/notebooks:/srv
      - ./tagger:/srv/lib
    depends_on:
      - elasticsearch-geo

  tagger-geo:
    build: tagger
    ports:
      - 16000:5000
    volumes:
      - ./tagger:/krypton
    depends_on:
      - elasticsearch-geo

networks:
  im:
    external: true
