version: "3.1"
services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "80:5601"
    depends_on:
      - elasticsearch

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/v_mdg_vias-template.json:/etc/logstash/templates/v_mdg_vias-template.json
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx500m -Xms500m"

  jupyter:
    image: jupyter-im
    build: jupyter/
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/notebooks:/srv
    depends_on:
      - elasticsearch

#  tagger:
#    build: tagger
#    ports:
#      - 5000:5000
#    volumes:
#      - ./tagger/libs:/krypton
#    environment:
#      - MONGO_GEO_STRING=mongodb://mongo/im
#    networks:
#      - im

networks:
  im:
    external: true
