FROM gw000/keras-full

RUN pip3 --no-cache-dir install -U spacy
RUN python3 -m spacy download es_core_news_md
RUN pip install elasticsearch shapely
RUN pip3 install elasticsearch shapely
#RUN pip3 uninstall -y numpy
#RUN pip3 --no-cache-dir install anytree nltk gensim unidecode
#RUN pip3 --no-cache-dir install ipywidgets



